install.packages("neuralnet")
install.packages("nnet")
install.packages("ggplot2")
install.packages("bigmemory")
install.packages("doParallel")
install.packages("astsa")
install.packages("caret")
install.packages("e1071")
